#!/usr/bin/env node
import { writeFile, mkdir } from "node:fs/promises";
import { McpClient, resultText } from "./client.js";
import { CredentialError } from "./credentials.js";
import { openSession, listServers } from "./resolver.js";
import { generateModule } from "./codegen.js";

const USAGE = `agent-codemode — call the MCP servers Claude Code is authenticated to
Installed as both \`agent-codemode\` and the shorter \`codemode\`.

  codemode servers                       list every server (config files + Keychain)
  codemode tools <server>                list a server's tools
  codemode call <server> <tool> [args]   call a tool
  codemode types <server> [--out file]   generate a .ts types module for a server
  codemode types --all [--out dir]       generate a module per authed server + index barrel
  codemode types --url <url> [--name n]  generate for a raw endpoint (unauthenticated tools/list)

Arguments for "call" (combine freely; later values win):
  --json '{"a":1}'      whole argument object as JSON
  --arg key=value       one string argument
  --arg key:=1          one JSON-valued argument (number, bool, array, object)

Options:
  --text                print only the text content of the result
  --raw                 print the whole JSON-RPC result (default)
  -h, --help            this message

Examples:
  codemode servers
  codemode tools linear
  codemode call linear list_issues --arg team="Hyre Ops" --arg state=Todo --text
  codemode call linear list_issues --json '{"team":"Hyre Ops","limit":5}'

Notes:
  Tokens are read fresh from the macOS Keychain on every run and are never
  printed. Claude Code owns token refresh: if one has expired, start Claude Code
  or run \`claude mcp login <server>\`.
`;

function parseCallArgs(argv: string[]): Record<string, unknown> {
  const args: Record<string, unknown> = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--json") {
      const raw = argv[++i];
      if (raw === undefined) throw new Error("--json needs a value");
      const parsed = JSON.parse(raw);
      if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) {
        throw new Error("--json must be a JSON object");
      }
      Object.assign(args, parsed);
    } else if (a === "--arg") {
      const pair = argv[++i];
      if (pair === undefined) throw new Error("--arg needs key=value or key:=json");
      const jsonSep = pair.indexOf(":=");
      const strSep = pair.indexOf("=");
      if (jsonSep !== -1 && (strSep === -1 || jsonSep < strSep)) {
        args[pair.slice(0, jsonSep)] = JSON.parse(pair.slice(jsonSep + 2));
      } else if (strSep !== -1) {
        args[pair.slice(0, strSep)] = pair.slice(strSep + 1);
      } else {
        throw new Error(`--arg "${pair}" is not key=value or key:=json`);
      }
    } else if (a === "--text" || a === "--raw") {
      // handled by the caller
    } else {
      throw new Error(`unexpected argument: ${a}`);
    }
  }
  return args;
}

async function main(argv: string[]): Promise<number> {
  if (argv.length === 0 || argv[0] === "-h" || argv[0] === "--help") {
    process.stdout.write(USAGE);
    return 0;
  }

  const [command, ...rest] = argv;

  if (command === "servers") {
    const servers = await listServers();
    if (servers.length === 0) {
      process.stderr.write("No MCP servers found in the config files or the Keychain.\n");
      return 1;
    }
    for (const s of servers) {
      const auth =
        s.auth === "oauth" ? `oauth:${s.tokenState ?? "?"}` : s.auth === "header" ? "api-key" : s.auth;
      process.stdout.write(
        `${s.name.padEnd(22)} ${s.client.padEnd(9)} ${s.transport.padEnd(5)} ${auth.padEnd(16)} ${s.detail}\n`,
      );
    }
    return 0;
  }

  if (command === "tools") {
    const server = rest[0];
    if (!server) throw new Error("usage: codemode tools <server>");
    const session = await openSession(server);
    try {
      const tools = await session.listTools();
      process.stdout.write(JSON.stringify(tools, null, 2) + "\n");
    } finally {
      await session.close();
    }
    return 0;
  }

  if (command === "types") {
    const flag = (name: string) => {
      const i = rest.indexOf(name);
      return i !== -1 ? rest[i + 1] : undefined;
    };
    const out = flag("--out");
    const urlArg = flag("--url"); // generate for a raw endpoint (e.g. an unauthenticated connector)

    // --all: generate one module per discovered server into a directory + a barrel.
    if (rest.includes("--all")) {
      const dir = flag("--out") ?? "mcp-types";
      await mkdir(dir, { recursive: true });
      const servers = await listServers();
      const barrel: string[] = ["// Generated by agent-codemode types --all. Do not edit by hand."];
      let skipped = 0;
      for (const s of servers) {
        // Opening the session is itself fallible — an expired token throws here,
        // not at listTools. It has to be inside the try, or one stale server
        // takes down the whole sweep.
        let session;
        try {
          session = await openSession(s.name);
          const tools = await session.listTools();
          const mod = generateModule(s.name, tools);
          const file = `${s.name.replace(/[^a-zA-Z0-9]+/g, "-")}.ts`;
          await writeFile(`${dir}/${file}`, mod.source);
          barrel.push(`export * from "./${file.replace(/\.ts$/, ".js")}";`);
          process.stderr.write(`${s.name.padEnd(22)} ${mod.methods.length} methods\n`);
        } catch (e) {
          skipped++;
          process.stderr.write(`${s.name.padEnd(22)} skipped — ${(e as Error).message.split(".")[0]}\n`);
        } finally {
          await session?.close();
        }
      }
      await writeFile(`${dir}/index.ts`, barrel.join("\n") + "\n");
      process.stderr.write(
        `\nwrote ${dir}/ (with index.ts barrel)${skipped ? ` — ${skipped} skipped\n` : "\n"}`,
      );
      // Nothing generated at all is a failure, not a quiet success.
      return barrel.length > 1 ? 0 : 1;
    }

    const server = rest.find((r) => !r.startsWith("--") && rest.indexOf(r) === 0);
    let tools;
    let label: string;
    if (urlArg) {
      label = flag("--name") ?? new URL(urlArg).hostname.split(".")[0];
      tools = await McpClient.fromUrl(urlArg).listTools();
    } else if (server) {
      label = server;
      const session = await openSession(server);
      try {
        tools = await session.listTools();
      } finally {
        await session.close();
      }
    } else {
      throw new Error("usage: codemode types <server> [--out file] | --all | --url <url> [--name n]");
    }
    const mod = generateModule(label, tools);
    if (out) {
      await writeFile(out, mod.source);
      process.stderr.write(`wrote ${mod.methods.length} typed methods to ${out}\n`);
    } else {
      process.stdout.write(mod.source);
    }
    return 0;
  }

  if (command === "call") {
    const [server, tool, ...argv2] = rest;
    if (!server || !tool) throw new Error("usage: codemode call <server> <tool> [args]");
    const wantText = argv2.includes("--text");
    const args = parseCallArgs(argv2);
    const session = await openSession(server);
    let result;
    try {
      result = await session.callTool(tool, args);
    } finally {
      await session.close();
    }
    if (wantText) {
      const text = resultText(result);
      process.stdout.write((text ?? JSON.stringify(result)) + "\n");
    } else {
      process.stdout.write(JSON.stringify(result, null, 2) + "\n");
    }
    // A tool that reports its own failure must not look like success.
    return result.isError ? 2 : 0;
  }

  throw new Error(`unknown command "${command}". Run --help.`);
}

/**
 * Wait for a stream's buffered writes to reach the OS.
 *
 * Node's stdout is asynchronous when it is a pipe, so `process.exit()` right
 * after a large `write()` discards whatever is still buffered — in practice
 * everything past the 64 KiB pipe buffer. `codemode tools linear | jq` loses
 * half its output that way, silently, which is the one failure mode this tool
 * refuses to have. An empty write's callback fires after the queued writes
 * ahead of it have flushed, so awaiting it is enough.
 */
function drain(stream: NodeJS.WriteStream): Promise<void> {
  if (stream.writableLength === 0) return Promise.resolve();
  return new Promise((resolve) => stream.write("", () => resolve()));
}

async function exit(code: number): Promise<never> {
  await Promise.all([drain(process.stdout), drain(process.stderr)]);
  process.exit(code);
}

main(process.argv.slice(2))
  .then(exit)
  .catch((err: unknown) => {
    const msg = err instanceof Error ? err.message : String(err);
    process.stderr.write(`${err instanceof CredentialError ? "credential error" : "error"}: ${msg}\n`);
    return exit(1);
  });
